UI:
  descriptions:
    alip: ARM Internet Platform
    choice:
      build: The build (alpha-1 / beta / final) or date of snapshot (YYYYMMDD:build_number or 'latest')
        to fetch.
      hardware: The board you are building the image to run on.
      hwpack: The hardware pack to use when building the image.
      image: A distribuion image, e.g. headless.
      platform: Which Linaro platform to build an image from. Specify 'snapshot' to
        use a snapshot rather than a release.
    developer: Developer Tools
    o-developer: Developer Tools
    graphics: Graphics
    o-graphics: Graphics
    multimedia: Multimedia
    o-multimedia: Multimedia
    nano: Nano
    o-nano: Nano
    ubuntu-desktop: 'LEB: Linaro Ubuntu Desktop'
    o-ubuntu-desktop: 'LEB: Linaro Ubuntu Desktop'
    ubuntu-desktop::long: Linux for humans on low power machines
    ubuntu-desktop::release_note: Shiny!
    o-alip: ARM Linux Internet Platform
    alip: ARM Linux Internet Platform
    server: Server
    o-server: Server
  hwpack-descriptions:
    omap3: Basic support for Beagle boards
    omap3-x11-base: Includes support for 3D acceleration
    overo: Same kernel as omap3.
    panda: Basic support for Panda from linux-linaro-3.0
    panda-x11-base: Basic support for Panda from linux-linaro-3.0 plus support for 3D acceleration
    bsp-omap4: (DEPRECATED) - Used in Maverick release
    lt-panda: TI Landing Team kernel (kernel-tilt.git)
    lt-panda-x11-base-natty: TI Landing Team kernel (kernel-tilt.git) plus support for 3D acceleration
    s5pv310: Support for this has been dropped in order to focus development efforts on Origen
    lt-s5pv310: Support for this has been dropped in order to focus development efforts on Origen

  help:
    latest snapshot: Latest Snapshot help text
    release: Release help text
    snapshot: Snapshot help text
  translate:
  cmdline short names:
    build: b
    hardware: w
    platform: a
    image: i
    hwpack: p
choice:
  build: {}
  hardware:
    beagle: Beagle Board
    igep: IGEPv2
    panda: Panda Board
    vexpress: Versatile Express
    ux500: UX500
    efikamx: EFIKA MX Smarttop 
    efikasb: EFIKA MX Smartbook
    mx51evk: i.MX51
    mx53loco: i.MX53 Quick Start
    # I don't have a --dev setting to linaro-media-create for a u8500 yet.
    # u8500: U8500
    overo: Overo
    smdkv310: S5PV310
    origen: Origen
    # UI may need some work to support snowball. Currently under investigation.
    #snowball_sd: Snowball
  
  hwpack:
    beagle:
    - omap3
    - omap3-x11-base
    - omap3-oneiric
    - omap3-x11-base-oneiric
    
    igep:
    - igep
    - igep-oneiric
    
    panda:
    - panda
    - panda-x11-base
    - bsp-omap4
    - lt-panda-x11-base-natty
    - lt-panda
    - panda-oneiric
    - panda-x11-base-oneiric
    - lt-panda-x11-base-oneiric
    - lt-panda-oneiric
    
    vexpress:
    - vexpress
    - vexpress-oneiric
    - lt-vexpress-a9-oneiric
    
    ux500:
    - bsp-ux500
    
    efikamx:
    - efikamx
    - efikamx-oneiric
    
    efikasb:
    - efikamx
    - efikamx-oneiric
    
    mx51evk:
    - imx51
    - imx51-oneiric
    
    mx53loco:
    - lt-mx5
    - lt-mx5-oneiric
     
    u8500:
     - lt-u8500
     
    overo:
    - overo
    - overo-oneiric
     
    smdkv310:
     - lt-s5pv310
     - s5pv310

    origen:
     - lt-origen
     - lt-origen-oneiric

    snowball_sd:
     - lt-snowball
     - lt-snowball-v2
     - lt-snowball-v3-oneiric
     - lt-snowball-v2-oneiric

  image:
  - alip
  - developer
  - headless
  - ubuntu-desktop
  platform:
    linaro-m:
    - final
    linaro-n:
    - alpha-1
    - alpha-2
    - alpha-3
    - beta
    - rc
    - final

  platform:
    '11.05':
    - final
    '11.06':
    - final
    '11.07':
    - final
    '11.08':
    - final
    '11.09':
    - final
    '11.10':
    - final

platform: linaro-n
repository: release


